[package]
name = "mctext-example"
version = "0.1.0"
edition = "2024"
publish = false

[workspace]

[[bin]]
name = "example"
path = "example.rs"

[dependencies]
mctext = { path = "../crates/mctext", features = ["render"] }
image = "0.25"
